// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteLayout(arg1:number):Promise<void>;

export function GetActiveLayout():Promise<models.Layout>;

export function GetAllLayouts():Promise<Array<models.Layout>>;

export function GetAllSettings():Promise<Array<models.Setting>>;

export function GetLayout(arg1:number):Promise<models.Layout>;

export function GetSetting(arg1:string):Promise<string>;

export function GetWindowState():Promise<models.WindowState>;

export function Greet(arg1:string):Promise<string>;

export function SaveLayout(arg1:string,arg2:string):Promise<models.Layout>;

export function SaveWindowState(arg1:number,arg2:number,arg3:number,arg4:number,arg5:boolean):Promise<void>;

export function SetActiveLayout(arg1:number):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;
