// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteLayout(arg1) {
  return window['go']['main']['App']['DeleteLayout'](arg1);
}

export function GetActiveLayout() {
  return window['go']['main']['App']['GetActiveLayout']();
}

export function GetAllLayouts() {
  return window['go']['main']['App']['GetAllLayouts']();
}

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetLayout(arg1) {
  return window['go']['main']['App']['GetLayout'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetWindowState() {
  return window['go']['main']['App']['GetWindowState']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveLayout(arg1, arg2) {
  return window['go']['main']['App']['SaveLayout'](arg1, arg2);
}

export function SaveWindowState(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveWindowState'](arg1, arg2, arg3, arg4, arg5);
}

export function SetActiveLayout(arg1) {
  return window['go']['main']['App']['SetActiveLayout'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}
